"""Agregar columnas a deudas

Revision ID: 3925033a9db0
Revises: e030cf707aea
Create Date: 2025-09-11 15:33:17.231741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3925033a9db0'
down_revision: Union[str, Sequence[str], None] = 'e030cf707aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deudas', sa.Column('volante_id', sa.Integer(), nullable=True))
    op.add_column('deudas', sa.Column('impresion_id', sa.Integer(), nullable=True))
    op.add_column('deudas', sa.Column('cantidad_excedida', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deudas', 'volantes', ['volante_id'], ['id'])
    op.create_foreign_key(None, 'deudas', 'impresiones', ['impresion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deudas', type_='foreignkey')
    op.drop_constraint(None, 'deudas', type_='foreignkey')
    op.drop_column('deudas', 'cantidad_excedida')
    op.drop_column('deudas', 'impresion_id')
    op.drop_column('deudas', 'volante_id')
    # ### end Alembic commands ###
