"""add tipo column to deudas

Revision ID: e030cf707aea
Revises: 
Create Date: 2025-09-11 13:33:22.294375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e030cf707aea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deudas', sa.Column('tipo', sa.String(), nullable=True))
    op.add_column('pagos', sa.Column('metodo', sa.String(), nullable=True))
    op.add_column('pagos', sa.Column('referencia', sa.String(), nullable=True))
    op.add_column('pagos', sa.Column('capture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos', 'capture_url')
    op.drop_column('pagos', 'referencia')
    op.drop_column('pagos', 'metodo')
    op.drop_column('deudas', 'tipo')
    # ### end Alembic commands ###
